apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamaji-tcp-health-exporter
    #  namespace: cattle-monitoring-system
  labels:
    app: kamaji-tcp-health-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kamaji-tcp-health-exporter
  template:
    metadata:
      labels:
        app: kamaji-tcp-health-exporter
    spec:
      containers:
      - name: kamaji-tcp-health-exporter
        image: febri4n/kamaji-tcp-health-exporter:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kamaji-tcp-health-exporter-service
    #  namespace: cattle-monitoring-system
spec:
  type: ClusterIP
  selector:
    app: kamaji-tcp-health-exporter
  ports:
    - port: 80
      targetPort: 8080
      name: http
