apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kamaji-tcp-health-exporter
  name: kamaji-tcp-health-exporter
  namespace: default
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: kamaji-tcp-health-exporter
